---
logging:
  #pattern:
  #console: %d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n
  level:
    root: INFO
logging.level.org.hibernate.SQL: INFO
---
server:
  port: 8080
  http2.enabled: true
  compression.enabled: true
  servlet:
    context-path: /productServices
---
spring:
  profiles:
    active: CONSOLA